config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'privacy', to: 'static_pages#privacy'
  get 'userpolicy', to: 'static_pages#userpolicy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get '/logout' => 'user_sessions#destroy'

  resources :users
  resources :shops, only: %i[index show] do
    collection do
      get :likes
    end
    resources :likes, only: %i[create destroy]
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :shop
  
    validates :user_id, uniqueness: { scope: :shop_id }
  end

app/models/shop.rb
class Shop < ApplicationRecord
 
  end

app/models/user.rb
class User < ApplicationRecord
    authenticates_with_sorcery!

    has_many :likes, dependent: :destroy
    has_many :liked_shops, through: :likes, source: :shop
  
    validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
    validates :email, uniqueness: true
    validates :email, presence: true
    validates :name, presence: true, length: { maximum: 255 }

    def like(shop)
      liked_shops << shop
    end
  
    def unlike(shop)
      liked_shops.delete shop
    end
  
    def like?(shop)
      liked_shops.include? shop
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    shop = Shop.find params[:shop_id]
    current_user.like(shop)
    redirect_to shops_path
  end
  
  def destroy
    shop = Shop.find params[:shop_id]
    current_user.unlike(shop)
    redirect_to shops_path
  end

  def show
    @liked_shops = current_user.liked_shops
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
    
  end

  def likes
    @liked_shops = current_user.liked_shops
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    def new; end
  
    def create
      @user = login(params[:email], params[:password])
      if @user
        redirect_back_or_to root_path
      else
        render :new
      end
    end
  
    def destroy
      logout
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to login_path
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hitokara</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class='navbar navbar-expand-md top-logo nav-menu'>
    <div class="container">
      <%= link_to root_path, class: 'navbar-brand text-white header-font','data-turbolinks': false do %>
      <% end %>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-md-flex">
          <%= link_to 'ログイン', login_path, class: 'dropdown-item', method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer>
<div class='container text-center pt-2'>
  <div class='row'>
  <%= link_to "https://twitter.com/share?url=#{request.url}&text=%23ヒトカラ部%20はヒトカラ専門店を簡単に探せるサービスです。", title: 'Twitter', target: '_blank', class: 'text-brack p-1 col-sm' do %>
      <i class="fab fa-twitter"></i>
    <% end %>
    <ul class="navbar-nav">
      <li class="nav-item d-md-flex">
          <%= link_to '利用規約', userpolicy_path, class: 'dropdown-item' %>
          <%= link_to 'プライバシーポリシー', privacy_path, class: 'dropdown-item' %>
          <%= link_to 'お問い合わせ', 'https://docs.google.com/forms/d/1e2S1gSegArLdS1KuOPPnDHS4iBizNUCeykfBD-hn0xM/edit', class: 'dropdown-item' %>
      </li>
    </ul>
  </div>
</div>
<div class='row'>
    <div class='text-center col-12 pt-2'>
      <p>Copyright © 2022 ヒトカラ部</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-md top-logo nav-menu'>
    <div class="container">
      <%= link_to root_path, class: 'navbar-brand text-white header-font','data-turbolinks': false do %>
        
      <% end %>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-md-flex">
          <%= link_to '地図から探す', '#', class: 'dropdown-item' %>
          <%= link_to 'ヒトカラ専門店一覧', shops_path, class: 'dropdown-item' %>
          <%= link_to 'いいね一覧', likes_shops_path, class: 'dropdown-item' %>
          <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_form.html.erb
<%= search_field @q, url: url do |f| %>
  <div class='input-group'>
    <div class="col-5 d-inline-block mb-2  pr-0">
      <%= f.search_field :name_or_address_cont, method: :get, local: true, class: "form-control text-justify", placeholder: "地名・店名" %>
    </div>
    <div class="col-5 d-inline-block pr-0">
      <%= f.select :address_cont, options_from_collection_for_select(Prefecture.all, :name, :name), { include_blank: '都道府県を選択' }, { class: 'form-control text-justify' } %>
    </div>
    <div class="d-inline-block input-group-append">
      <%= f.submit '検索', class: "col-auto btn btn-dark"%>
    </div>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<tr>
  <td><%= shop.name %></td>
  <td><%= shop.phone_number %></td>
  <td><%= shop.address %></td>
  <% if current_user.like?(shop) %>
  <td><%= link_to 'いいね解除', shop_like_path(shop,shop), data: { turbo_method: :delete } %></td>
  <% else %>
  <td><%= link_to 'いいね', shop_likes_path(shop), data: { turbo_method: :post } %></td>
  <% end %>
</tr>

app/views/shops/index.erb
<div class="container pt-3">
  <div class="row">
    <div class='table-responsive'>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">店名</th>
            <th scope="col">電話番号</th>
            <th scope="col">住所</th>
          </tr>
        </thead>
        <tbody>
          <% @shops.each do |shop| %>
            <%= render 'shop', shop: shop %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<h1>ヒトカラ専門店一覧</h1>
<div class="container pt-3">
  <div class="row">
    <div class='table-responsive'>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">店名</th>
            <th scope="col">電話番号</th>
            <th scope="col">住所</th>
          </tr>
        </thead>
        <tbody>
          <% @shops.each do |shop| %>
            <%= render 'shop', shop: shop %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shops/likes.html.erb
<h1>いいね一覧</h1>
<div class="container pt-3">
  <div class="row">
    <div class='table-responsive'>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">店名</th>
            <th scope="col">電話番号</th>
            <th scope="col">住所</th>
          </tr>
        </thead>

        <tbody>
        <% @liked_shops.each do |shop| %>
        <tr>
            <td><%= shop.name %></td>
            <td><%= shop.phone_number %></td>
            <td><%= shop.address %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
   </div>
</div>

app/views/static_pages/privacy.html.erb
<div class="container px-4 px-lg-5">
  <div class='mt-4'>
    <h1>プライバシーポリシー</h1>
  </div>
  <p class="mb-5">　本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
  </p>
  <div class="row gx-4 gx-lg-5">
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第1条（個人情報）</h2>
      <p>　「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第2条（個人情報の収集方法）</h2>
      <p>　本サービスは、ユーザーが利用登録をする際に氏名、生年月日、電話番号、メールアドレスなどの個人情報をお尋ねすることがあります。また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。
      本サービスは、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。</p>
      <ol>
        <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他、本サービスが利用登録を相当でないと判断した場合</li>
        </li>
      </ol>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第3条（個人情報を収集・利用する目的）</h2>
      <p>　本サービスが個人情報を収集・利用する目的は、以下のとおりです。</p>
      <ol>
        <li>サービスの提供・運営のため</li>
        <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
        <li>ユーザーが利用中のサービスの新機能、更新情報、キャンペーン等の案内のメールを送付するため</li>
        <li>メンテナンス、重要なお知らせなど必要に応じたご連絡のため</li>
        <li>利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため</li>
        <li>ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため</li>
        <li>上記の利用目的に付随する目的</li>
      </ol>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
    <h2>第4条（利用目的の変更）</h2>
      <p>　次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。
      </p>
      <ol>
        <li>人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
        <li>予め次の事項を告知あるいは公表し、かつ当社が個人情報保護委員会に届出をしたとき</li>
          <ol>
            <li>利用目的に第三者への提供を含むこと</li>
            <li>第三者に提供されるデータの項目</li>
            <li>第三者への提供の手段または方法</li>
            <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
            <li>本人の求めを受け付ける方法</li>
          </ol>
        </li>
      </ol>
      <p>　前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。
      </p>
      <ol>
        <li>本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
        <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
        <li>個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いた場合</li>
      </ol>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第5条（個人情報の訂正および削除）</h2>
      <p>　ユーザーは、本サービスにて保有する自己の個人情報が誤った情報である場合には、、本サービスに対して個人情報の訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。
      ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正等を行うものとします。
      前項の規定に基づき訂正等を行った場合、または訂正等を行わない旨の決定をしたときは遅滞なく、これをユーザーに通知します。
      </p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
    <h2>第6条（個人情報の利用停止等）</h2>
      <p>　本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行います。
      前項の調査結果に基づき、その請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の利用停止等を行います。
      前項の規定に基づき利用停止等を行った場合、または利用停止等を行わない旨の決定をしたときは、遅滞なく、これをユーザーに通知します。
      前2項にかかわらず、利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じるものとします。
      </p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第7条（アクセス解析ツール）</h2>
      <p>　本サービスは、お客様のアクセス解析のために「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。
      このデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができますので、詳しくはお使いのブラウザの設定をご確認ください。
      Googleアナリティクスについて、詳しくは<%= link_to 'Googleアナリティクス利用規約', 'https://marketingplatform.google.com/about/analytics/terms/jp/' %>をご確認ください。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第8条（プライバシーポリシーの変更）</h2>
      <p>　本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。
      変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。</p>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="container px-4 px-lg-5">
  <div class='mt-4'>
    <h1>ヒトカラ部</h1>
  </div>
  <p class="mb-12">ヒトカラ部は、一人カラオケ専門店を簡単に検索出来るサービスです。
  </p>
  <p class="mb-12">
  </p>
</div>

app/views/static_pages/userpolicy.html.erb
<div class="container px-4 px-lg-5">
   <div class='mt-4'>
    <h1>利用規約</h1>
  </div>

  <p class="mb-5">　この利用規約（以下、「本規約」といいます。）は、このウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。本サービスのご利用ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って本サービスをご利用いただきます。</p>
  <div class="row gx-4 gx-lg-5">
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第1条（適用）</h2>
      <p>　本規約は、本サービスの利用に関わる一切の関係に適用されるものとします。
      本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。
      本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第2条（禁止事項）</h2>
      <p>　本サービスの利用にあたり、以下の行為をしてはなりません。</p>
      <ol>
        <li>法令または公序良俗に違反する行為</li>
        <li>犯罪行為に関連する行為</li>
        <li>本サービスの内容等、本サービスに含まれる著作権、商標権ほか知的財産権を侵害する行為</li>
        <li>本サービス、ほかのユーザー、またはその他第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
        <li>本サービスによって得られた情報を商業的に利用する行為</li>
        <li>本サービスの運営を妨害するおそれのある行為</li>
        <li>不正アクセス、またはこれを試みる行為</li>
        <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li>不正な目的を持って本サービスを利用する行為</li>
        <li>本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為</li>
        <li>他のユーザーに成りすます行為</li>
        <li>本サービス上での宣伝、広告、勧誘、または営業行為</li>
        <li>本サービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>その他、本サービスにて不適切と判断される行為</li>
      </ol>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第3条（本サービスの提供の停止等）</h2>
      <p>　以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
      <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他、本サービスの提供が困難と判断した場合</li>
      </ol>
      <p>　本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第4条（保証の否認および免責事項）</h2>
      <p>　本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。
      本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。
      </p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第5条（サービス内容の変更等）</h2>
      <p>　ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。
      </p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第6条（利用規約の変更）</h2>
      <p>　本サービスは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。
      </p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第7条（個人情報の取扱い）</h2>
      <p>　本サービスの利用によって取得する個人情報については、プライバシーポリシーに従い適切に取り扱うものとします。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第8条（権利義務の譲渡の禁止）</h2>
      <p>　ユーザーは本サービス運営の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>
    </div>
    <div class="col-md-10 col-lg-10 mx-auto mb-5">
      <h2>第9条（準拠法・裁判管轄）</h2>
      <p>　本規約の解釈にあたっては、日本法を準拠法とします。</p>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'ログイン', class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
        <a href="#">パスワードをお忘れの方はこちら</a>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>